### ISSUE TITLE
Missing classes for archives/archival documents

### ISSUE THREAD

**Issue by mromanello** [SPAROntologies/fabio#1]
Hi,

as discussed with @essepuntato over Skype some days ago, I'd like to propose adding to the ontology some classes to represent **archives/archival documents**.

The need for such classes emerged in the context of the [Linked Books project](https://dhlab.epfl.ch/page-127959-en.html), and especially the RDF export we are currently working on, to dump all of our citation data in a format compliant with the [Open Citation Corpus data model](http://opencitations.net/model).

We are having the following use case:
- some of the _cited_ publications (`bibliographic resources`) in our corpus are primary sources, and especially archival documents (e.g. documents preserved in the Venice State Archive)
- we'd like to use a `fabio` class to characterize such bibl. resources in the same way we are using `fabio:JournalArticle` and `fabio:Book`.

Minimal proposition:
- add an `ArchivalDocument` class (see below for the names) as a sub-class of `fabio:Expression`
- add an `Archive` class, which could be a specialization of `fabio:DocumentRepository`
- `partOf`/ `contains` relations could exist between an instance of `Archive` and one or more instances of `ArchivalDocument`, to group the sources by the archive they belong to.
 
As for the names/labels:
- some ideas: `ArchivalDocument`, `ArchivalExpression`, `ArchivalSource` although this last one seems more problematic as "being a source for" is more a role than it is a type.

What do you think?

matteo

**Comment by davidshotton** [comment]
Your suggestions sound very sensible, and we should use the name ArchivalDocument.  However, this must be understood only to mean that this document is in an Archive, NOT that it is old, unique, or has any other special properties.  Those (if you need them) must be defined separately.

**Comment by mromanello** [comment]
Hi @davidshotton 

I totally agree with you. The `ArchivalDocument` class serves merely to express citation data that involve references to primary sources. To express any additional information about the sources themselves we'll probably be using the RiC ([Record in Contexts](https://www.ica.org/en/egad-ric-conceptual-model)) ontology -- as soon as a first version is released.

**Comment by essepuntato** [comment]
@mromanello in order to add the classes in FaBiO, I would need a clear definition to both "Archive" and "ArchivalDocument". Could you please provide them, just to start to elaborate a bit more on them?

**Comment by mromanello** [comment]
thanks for flagging this up @essepuntato ! 

Now that I think more carefully about it, I'd rather call it `ArchivalRecord` than `ArchivalDocument`, if you agree?

I like the definition of *archival record* by the Society of American Archivists (emphasis is my own):

> Materials created or received by a person, family, or organization, public or private, in the conduct of their affairs that are preserved because of the enduring value contained in the information they contain or as evidence of the functions and responsibilities of their creator.
> 
> Notes:
**'Archival records' connotes documents rather than artifacts or published materials, although collections of archival records may contain artifacts and books**. Archival records may be in any format, including text on paper or in electronic formats, photographs, motion pictures, videos, sound recordings. The phrase archival records is sometimes used as an expanded form of archives to distinguish the holdings from the program.
> [SAA Glossary s.v. archival records](https://www2.archivists.org/glossary/terms/a/archival-records)

and I'd just stick to this.

As for `Archive`, as I mentioned a few comments ago, I don't think it's absolutely necessary in order to represent citation information (there are other ontologies taking care of this as well).

**Comment by essepuntato** [comment]
Hi @mromanello 

Some doubts about `ArchivalRecord`, which is something very very broad and, at a first sight, it seems for referring to the Work level rather than the Expression level -- where maybe `ArchivalDocument` works better. My question is: can an archival record being represented in different ways, e.g. as a document, as a record in a database, etc.?

I would like to hear what @davidshotton thinks here. It would be even possible to add both the classes at work and expression levels.

What do you think?

**Comment by mromanello** [comment]
Hi @essepuntato and @davidshotton 

At long last, coming back to this issue, sorry for the hiatus.

> My question is: can an archival record being represented in different ways, e.g. as a document, as a record in a database, etc.?

My spontaneous answer will be 'yes'. But your comment had me thinking also about the distinction between `ArchivalRecord` and `ArchivalRecordSet`. In our Venice Scholar data -- that we are mapping to the OC data model -- the references we have actually point to sets of archival records (e.g. an archival fund) rather than single archival records -- although this may change in the future.

But coming back to your original point, an archival record is "instantiated" in an archival document, but you could also have an image representing it, or a record in a database describing that archival record. So I guess you are right in saying `ArchivalRecord` refers more to the Work level.

This said, I understand that archives are not the main concern of FaBio, so we don't expect FaBio to provide a precise and exhaustive description of archives and their holdings. 

Does this make sense to you both?

**Comment by essepuntato** [comment]
Added the classes `ArchivalRecord` and `ArchivalRecordSet` (Work), and `ArchivalDocument` and `ArchivalDocumentSet` (Expression).
